name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - run: npm run build-ci --if-present
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: "${{ secrets.USERNAME }}"
          server: "${{ secrets.SERVER_IP }}"
          port: "7822"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./build/*"
          remote_path: "/home/jspowere/jspower-app/build"
